# ==============================================================
#  build_report.py
#
#  Reads config.txt and findings.csv and writes report.typ.
#  Do not edit this file.
#
#  To build your report, run build.bat or these two commands:
#    .venv\Scripts\python.exe build_report.py
#    typst compile report.typ
#
#  findings.csv columns:
#    section_number, section_title, finding_id,
#    location, description, photo
#
#  config.txt keys:
#    report_title  — e.g. "Property Inspection Report"
#    client_logo   — filename of client logo PNG in project root
#    firm_logo     — filename of firm logo PNG in project root
#    cover_photo   — filename of cover photo in photos/ folder
#
#  executive_summary.txt:
#    Plain text file. Edit freely. Paragraphs separated by a
#    blank line will render as separate paragraphs in the report.
# ==============================================================

import csv
import os

CONFIG_FILE  = "config.txt"
CSV_FILE     = "findings.csv"
EXEC_SUM     = "executive_summary.txt"
PHOTO_DIR    = "photos"
OUTPUT_FILE  = "report.typ"

# -------------------------------------------------------
#  Read config.txt  (KEY: Value lines)
# -------------------------------------------------------
config = {}
with open(CONFIG_FILE, encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith("#") and ":" in line:
            key, _, value = line.partition(":")
            config[key.strip()] = value.strip()

def cfg(key, default=""):
    return config.get(key, default)

# -------------------------------------------------------
#  Read executive_summary.txt
#  Blank lines become paragraph breaks in Typst.
# -------------------------------------------------------
exec_sum_paragraphs = []
if os.path.exists(EXEC_SUM):
    with open(EXEC_SUM, encoding="utf-8") as f:
        raw = f.read()
    for para in raw.strip().split("\n\n"):
        exec_sum_paragraphs.append(para.strip())
else:
    exec_sum_paragraphs = ["Executive summary not found. Please create executive_summary.txt."]

# -------------------------------------------------------
#  Load findings.csv grouped by section
# -------------------------------------------------------
sections = {}
section_order = []

with open(CSV_FILE, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        sec_num = row["section_number"].strip()
        if sec_num not in sections:
            sections[sec_num] = {
                "title":    row["section_title"].strip(),
                "findings": [],
            }
            section_order.append(sec_num)
        sections[sec_num]["findings"].append(row)

# -------------------------------------------------------
#  Escape text safely for Typst string literals
# -------------------------------------------------------
def e(text):
    return (
        text
        .replace("\\", "\\\\")
        .replace('"',  '\\"')
        .replace("#",  "\\#")
        .replace("[",  "\\[")
        .replace("]",  "\\]")
        .replace("@",  "\\@")
    )

def ln(text=""):
    return text + "\n"

# -------------------------------------------------------
#  Pre-escape all config values
# -------------------------------------------------------
proj_name    = e(cfg("project_name"))
firm_name    = e(cfg("firm_name"))
firm_addr    = e(cfg("firm_address"))
firm_ph      = e(cfg("firm_phone"))
firm_web     = e(cfg("firm_website"))
prop_name    = e(cfg("property_name"))
prop_addr    = e(cfg("property_address"))
rep_date     = e(cfg("report_date"))
proj_num     = e(cfg("project_number"))
insp_date    = e(cfg("inspection_date"))
prep_by      = e(cfg("prepared_by"))
rev_by       = e(cfg("reviewed_by"))
client       = e(cfg("client"))
report_title = e(cfg("report_title", "Property Inspection Report"))
client_logo  = cfg("client_logo")
firm_logo    = cfg("firm_logo")
cover_photo  = cfg("cover_photo")

out = []

# -------------------------------------------------------
#  Finding box size constants
# -------------------------------------------------------
PHOTO_HEIGHT = "3.01in"
BOX_INSET_X  = "11pt"
BOX_INSET_Y  = "8pt"
BOX_GAP      = "10pt"
PHOTO_COL    = "4.5in"
LOGO_HEIGHT  = "0.35in"

# -------------------------------------------------------
#  Build footer logo Typst snippets
# -------------------------------------------------------
if client_logo:
    client_logo_typ = f'image("{client_logo}", height: {LOGO_HEIGHT})'
else:
    client_logo_typ = '[]'

if firm_logo:
    firm_logo_typ = f'image("{firm_logo}", height: {LOGO_HEIGHT})'
else:
    firm_logo_typ = f'text(size: 8pt)[{firm_name}]'

# -------------------------------------------------------
#  PREAMBLE — colors, page, text, heading styles
# -------------------------------------------------------
out.append(ln("// AUTO-GENERATED by build_report.py — do not edit."))
out.append(ln("// Edit config.txt, findings.csv, or executive_summary.txt and re-run build.bat."))
out.append(ln())
out.append(ln("#let firm-blue = rgb(70, 12, 33)"))
out.append(ln("#let rule-gray  = rgb(180, 180, 180)"))
out.append(ln())
out.append(ln("#set page("))
out.append(ln('  paper: "us-letter",'))
out.append(ln("  margin: (top: 1in, bottom: 1in, left: 1in, right: 1in),"))
out.append(ln("  header: context {"))
out.append(ln("    if counter(page).get().first() > 1 {"))
out.append(ln("      set text(size: 8pt, fill: black)"))
out.append(ln("      grid("))
out.append(ln("        columns: (1fr, auto),"))
out.append(ln(f"        [*{proj_name}*  |  {report_title}],"))
out.append(ln(f"        align(right)[{firm_name}],"))
out.append(ln("      )"))
out.append(ln("      line(length: 100%, stroke: 0.4pt + rule-gray)"))
out.append(ln("    }"))
out.append(ln("  },"))
out.append(ln("  footer: context {"))
out.append(ln("    if counter(page).get().first() > 1 {"))
out.append(ln("      line(length: 100%, stroke: 0.4pt + rule-gray)"))
out.append(ln("      grid("))
out.append(ln("        columns: (1fr, 1fr, 1fr),"))
out.append(ln("        align: (left + horizon, center + horizon, right + horizon),"))
out.append(ln(f"        {client_logo_typ},"))
out.append(ln("        text(size: 8pt, fill: rule-gray)[Page #counter(page).display()],"))
out.append(ln(f"        {firm_logo_typ},"))
out.append(ln("      )"))
out.append(ln("    }"))
out.append(ln("  },"))
out.append(ln(")"))
out.append(ln())
out.append(ln('#set text(font: "Arial", size: 10pt)'))
out.append(ln("#set par(leading: 0.55em, justify: true)"))
out.append(ln())
out.append(ln("#show heading.where(level: 1): it => {"))
out.append(ln("  v(0.8em)"))
out.append(ln('  text(size: 14pt, weight: "bold", fill: black, it.body)'))
out.append(ln("  v(2pt)"))
out.append(ln("  line(length: 100%, stroke: 1pt + firm-blue)"))
out.append(ln("  v(0.4em)"))
out.append(ln("}"))
out.append(ln())
out.append(ln("#show heading.where(level: 2): it => []"))
out.append(ln())

# -------------------------------------------------------
#  COVER PAGE
# -------------------------------------------------------
out.append(ln("// ============ COVER PAGE ============"))
out.append(ln("#page(margin: (top: 1in, bottom: 1in, left: 1in, right: 1in), header: none, footer: none)["))
out.append(ln("  #rect(width: 100%, height: 6pt, fill: firm-blue)"))
out.append(ln("  #v(0.3in)"))
if firm_logo:
    out.append(ln("  #grid("))
    out.append(ln("    columns: (auto, 1fr),"))
    out.append(ln("    column-gutter: 10pt,"))
    out.append(ln("    align: (left + horizon, left + horizon),"))
    out.append(ln(f'    image("{firm_logo}", height: 0.62in),'))
    out.append(ln("    ["))
    out.append(ln(f'      #text(size: 13pt, weight: "bold", fill: black)[{firm_name}] \\'))
    out.append(ln(f"      #text(size: 9pt, fill: rule-gray)[{firm_addr}] \\"))
    out.append(ln(f"      #text(size: 9pt, fill: rule-gray)[{firm_ph}  |  {firm_web}]"))
    out.append(ln("    ],"))
    out.append(ln("  )"))
else:
    out.append(ln(f'  #text(size: 13pt, weight: "bold", fill: black)[{firm_name}]'))
    out.append(ln("  #linebreak()"))
    out.append(ln(f"  #text(size: 9pt, fill: rule-gray)[{firm_addr}]"))
    out.append(ln("  #linebreak()"))
    out.append(ln(f"  #text(size: 9pt, fill: rule-gray)[{firm_ph}  |  {firm_web}]"))
out.append(ln("  #v(0.2in)"))
out.append(ln("  #line(length: 100%, stroke: 0.4pt + rule-gray)"))
out.append(ln("  #v(0.15in)"))
if cover_photo:
    out.append(ln(f'  #image("{PHOTO_DIR}/{cover_photo}", width: 100%, height: 2.8in, fit: "cover")'))
else:
    out.append(ln("  #rect(width: 100%, height: 2.8in, fill: rgb(230,235,242), stroke: none)[]"))
out.append(ln("  #v(0.15in)"))
out.append(ln("  #line(length: 100%, stroke: 0.4pt + rule-gray)"))
out.append(ln("  #v(0.25in)"))
out.append(ln(f'  #text(size: 24pt, weight: "bold", fill: black)[{report_title}]'))
out.append(ln("  #linebreak()"))
out.append(ln("  #v(8pt)"))
out.append(ln(f"  #text(size: 15pt, fill: black)[{proj_name} / {prop_name}]"))
out.append(ln("  #linebreak()"))
out.append(ln("  #v(4pt)"))
out.append(ln(f"  #text(size: 10pt, fill: rule-gray)[{prop_addr}]"))
out.append(ln("  #v(0.15in)"))
if client_logo:
    out.append(ln(f'  #image("{client_logo}", height: 0.45in)'))
    out.append(ln("  #v(0.15in)"))
out.append(ln("  #grid("))
out.append(ln("    columns: (1.8in, 1fr), row-gutter: 10pt,"))
out.append(ln('    text(weight: "bold", fill: black)[Report Date:],     [' + rep_date + '],'))
out.append(ln('    text(weight: "bold", fill: black)[Project No.:],     [' + proj_num + '],'))
out.append(ln('    text(weight: "bold", fill: black)[Inspection Date:], [' + insp_date + '],'))
out.append(ln('    text(weight: "bold", fill: black)[Prepared By:],     [' + prep_by + '],'))
out.append(ln('    text(weight: "bold", fill: black)[Reviewed By:],     [' + rev_by + '],'))
out.append(ln('    text(weight: "bold", fill: black)[Client:],          [' + client + '],'))
out.append(ln("  )"))
out.append(ln("  #v(1fr)"))
out.append(ln("  #rect(width: 100%, height: 6pt, fill: firm-blue)"))
out.append(ln("]"))
out.append(ln())

# -------------------------------------------------------
#  TABLE OF CONTENTS
# -------------------------------------------------------
out.append(ln("// ============ TABLE OF CONTENTS ============"))
out.append(ln('#outline(title: "Table of Contents", indent: 1em, depth: 2)'))
out.append(ln("#pagebreak()"))
out.append(ln())

# -------------------------------------------------------
#  EXECUTIVE SUMMARY
# -------------------------------------------------------
out.append(ln("// ============ EXECUTIVE SUMMARY ============"))
out.append(ln("= Executive Summary"))
out.append(ln())
for para in exec_sum_paragraphs:
    out.append(ln(e(para)))
    out.append(ln())

out.append(ln("#pagebreak()"))
out.append(ln())

# -------------------------------------------------------
#  Helper: write one finding box into out[]
# -------------------------------------------------------
def write_finding(row):
    fid        = e(row["finding_id"].strip())
    loc        = e(row["location"].strip())
    desc       = e(row["description"].strip())
    photo_file = row["photo"].strip()

    if photo_file:
        out.append(ln(f'#let _photo = image("{PHOTO_DIR}/{photo_file}", width: 100%, height: {PHOTO_HEIGHT}, fit: "contain")'))
    else:
        out.append(ln(
            f"#let _photo = rect(width: 100%, height: {PHOTO_HEIGHT}, "
            "fill: rgb(240,240,240), stroke: 0.4pt + rgb(180,180,180), inset: 0pt)"
            "[#align(center + horizon)[#text(fill: rgb(150,150,150), size: 8pt)[No photo provided]]]"
        ))

    out.append(ln(f"#rect(width: 100%, stroke: 0.6pt + firm-blue, fill: white, inset: (x: {BOX_INSET_X}, y: {BOX_INSET_Y}))["))
    out.append(ln("  #grid(columns: (1fr, auto), column-gutter: 6pt,"))
    out.append(ln(f'    text(weight: "bold")[Finding {fid}],'))
    out.append(ln(f'    text(size: 8pt, style: "italic", fill: rgb(80,80,80))[Location: {loc}],'))
    out.append(ln("  )"))
    out.append(ln("  #v(4pt)"))
    out.append(ln("  #line(length: 100%, stroke: 0.3pt + rgb(200,200,200))"))
    out.append(ln("  #v(4pt)"))
    out.append(ln(f"  #grid(columns: (1fr, {PHOTO_COL}), column-gutter: 6pt,"))
    out.append(ln("    ["))
    out.append(ln('      #text(weight: "bold", size: 9pt, fill: black)[Observation] \\'))
    out.append(ln(f"      #text(size: 9pt)[{desc}]"))
    out.append(ln("    ],"))
    out.append(ln("    _photo,"))
    out.append(ln("  )"))
    out.append(ln("]"))

# -------------------------------------------------------
#  SECTIONS AND FINDINGS
# -------------------------------------------------------
for sec_num in section_order:
    sec       = sections[sec_num]
    sec_title = e(sec["title"])
    findings  = sec["findings"]

    out.append(ln(f"// ============ SECTION {sec_num}: {sec_title} ============"))
    out.append(ln("#page(margin: (top: 1in, bottom: 1in, left: 1in, right: 1in))["))
    out.append(ln(f"  == Section {e(sec_num)}: {sec_title}"))
    out.append(ln("  #v(1fr)"))
    out.append(ln("  #align(center)["))
    out.append(ln(f'    #text(size: 26pt, weight: "bold", fill: black)[Section {e(sec_num)}]'))
    out.append(ln("    #linebreak()"))
    out.append(ln("    #v(8pt)"))
    out.append(ln(f"    #text(size: 16pt, fill: black)[{sec_title}]"))
    out.append(ln("    #linebreak()"))
    out.append(ln("    #v(14pt)"))
    out.append(ln("    #line(length: 50%, stroke: 0.6pt + rule-gray)"))
    out.append(ln("  ]"))
    out.append(ln("  #v(1fr)"))
    out.append(ln("]"))
    out.append(ln())

    pairs = [findings[i:i+2] for i in range(0, len(findings), 2)]

    for pair in pairs:
        out.append(ln("// --- finding page ---"))
        out.append(ln("#page(margin: (top: 1in, bottom: 1in, left: 1in, right: 1in))["))
        out.append(ln("  #v(1fr)"))
        write_finding(pair[0])
        if len(pair) == 2:
            out.append(ln(f"  #v({BOX_GAP})"))
            write_finding(pair[1])
        out.append(ln("  #v(1fr)"))
        out.append(ln("]"))
        out.append(ln())

# -------------------------------------------------------
#  Write report.typ
# -------------------------------------------------------
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.writelines(out)

total = sum(len(s["findings"]) for s in sections.values())
print(f"  report.typ written — {len(section_order)} sections, {total} findings")
print(f"\nDone. Now run:  typst compile report.typ")
